# Generated by Django 4.0.4 on 2022-05-01 07:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_article_category'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ArticleComment',
        ),
    ]
