# Generated by Django 4.0.4 on 2022-05-01 09:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_articlecomment'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='thumbnail',
            field=models.URLField(default=''),
        ),
        migrations.AddField(
            model_name='articlecomment',
            name='thumbnail',
            field=models.URLField(default=''),
        ),
        migrations.AddField(
            model_name='book',
            name='thumbnail',
            field=models.URLField(default=''),
        ),
        migrations.AddField(
            model_name='bookcomment',
            name='thumbnail',
            field=models.URLField(default=''),
        ),
    ]
