# Generated by Django 4.0.4 on 2022-05-07 08:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0015_alter_article_category_alter_book_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='favorite_articles',
            field=models.ManyToManyField(blank=True, related_name='user_favorited', to='app.article'),
        ),
        migrations.AlterField(
            model_name='user',
            name='favorite_books',
            field=models.ManyToManyField(blank=True, related_name='user_favorited', to='app.book'),
        ),
        migrations.AlterField(
            model_name='user',
            name='finished_articles',
            field=models.ManyToManyField(blank=True, related_name='user_finished', to='app.article'),
        ),
        migrations.AlterField(
            model_name='user',
            name='finished_books',
            field=models.ManyToManyField(blank=True, related_name='user_finished', to='app.book'),
        ),
        migrations.AlterField(
            model_name='user',
            name='reading_articles',
            field=models.ManyToManyField(blank=True, related_name='user_read', to='app.article'),
        ),
        migrations.AlterField(
            model_name='user',
            name='reading_books',
            field=models.ManyToManyField(blank=True, related_name='user_read', to='app.book'),
        ),
    ]
