# Generated by Django 4.0.4 on 2022-05-07 13:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0016_alter_user_favorite_articles_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='finished_articles',
        ),
        migrations.RemoveField(
            model_name='user',
            name='reading_articles',
        ),
    ]
