# Generated by Django 4.0.4 on 2022-05-09 11:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0017_remove_user_finished_articles_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='articlecomment',
            name='thumbnail',
        ),
        migrations.RemoveField(
            model_name='bookcomment',
            name='thumbnail',
        ),
    ]
