# Generated by Django 4.0.4 on 2022-05-11 07:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0021_article_status_book_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='article',
            name='status',
        ),
        migrations.RemoveField(
            model_name='book',
            name='status',
        ),
    ]
